### ISSUE TITLE
Error during configuration

### ISSUE THREAD

**Issue by mengssui** [stereolabs/zed-pytorch#4]
Platform : windows10
CUDA: 10.2
pytorch : 1.5.1

```
D:\Program Files\Anaconda3\envs\pytorch1\lib\site-packages\torch\utils\cpp_extension.py:238: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
```
Then I use call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" 

**but another problem happen:**

Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    setup(
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\site-packages\setuptools\__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\site-packages\setuptools\command\bdist_egg.py", line 174, in run    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\site-packages\setuptools\command\bdist_egg.py", line 160, in call_command
    self.run_command(cmdname)
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\site-packages\torch\utils\cpp_extension.py", line 603, in build_extensions
    build_ext.build_extensions(self)
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\site-packages\torch\utils\cpp_extension.py", line 576, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\site-packages\torch\utils\cpp_extension.py", line 1145, in _write_ninja_file_and_compile_objects
    _write_ninja_file(
  File "D:\Program Files\Anaconda3\envs\pytorch1\lib\site-packages\torch\utils\cpp_extension.py", line 1583, in _write_ninja_file
    assert len(sources) > 0
AssertionError

wish your help and suggestion.

**Comment by zly9120** [comment]
did you solve it?
